#!/data/data/com.termux/files/usr/bin/bash

# Get the URL
URL=$1

clear

# Check if its spotify URL or not.
# if it is then execute spotifydl command to download.

echo $URL

if [[ $URL == *"open.spotify.com"* ]]; then
    SONG_DIR="$HOME/storage/shared/songs" #for Termux only
    NODE_ENV=$(which node)
    SPOTIFYDL=$(which spotifydl)

    echo "Alphafy starting..."
    # check if directory exist or not
    if [[ ! -d $SONG_DIR ]]; then
        # directory doesn't exist create it for use.
        mkdir $SONG_DIR
    fi
    # Download the song to song directory.
    $NODE_ENV $SPOTIFYDL $URL -o $SONG_DIR

    read -n 1 -s -p "Press any key to exit..."
fi